### ISSUE TITLE
在华为P8 (with EMUI 3.1) 上运行Demo闪退

### ISSUE THREAD

**Issue by logan676** [8tory/weibo-android-sdk#5]
目前的微博SDK应该是不支持P8 EMUI 3.1和魅族MX5 Flyme 4.5.x系列的机型。SSO登录（有客户端）和第三方分享功能都无法在这两个ROM上正常运行。在Android Studio中运行Demo时，应用启动后，点击任何一个按钮，比如“微博授权”，都会“闪退”。但是后台的日志并不是常见的那种崩溃日志。而是类似于如下的格式。

```
10-19 16:59:42.410    3369-3509/? E/WifiStateMachine﹕ ConnectedState !RSSI_PKTCNT_FETCH uid=1000 0 0 "Office-Wifi-1" 70:ba:ef:c6:00:71 rssi=-36 f=2462 sc=100 link=72 tx=0.1, 0.0, 0.0  rx=2.6 bcn=0 [on:0 tx:0 rx:0 period:976] from screen [on:0 period:2136170963] gl u24 rssi=-35 ag=0 hr ls-=0 [56,56,56,56,61] brc=0 lrc=0
10-19 16:59:42.410    3369-3509/? E/WifiStateMachine﹕ L2ConnectedState !RSSI_PKTCNT_FETCH uid=1000 0 0 "Office-Wifi-1" 70:ba:ef:c6:00:71 rssi=-36 f=2462 sc=100 link=72 tx=0.1, 0.0, 0.0  rx=2.6 bcn=0 [on:0 tx:0 rx:0 period:3] from screen [on:0 period:2136170966] gl u24 rssi=-35 ag=0 hr ls-=0 [56,56,56,56,61] brc=0 lrc=0
10-19 16:59:42.430    3369-3509/? E/WifiStateMachine﹕ fetchRssiLinkSpeedAndFrequencyNative rssi=-37 linkspeed=72 SSID="Office-Wifi-1"
10-19 16:59:43.410    3369-3509/? E/WifiStateMachine﹕ ConnectedState !RSSI_PKTCNT_FETCH uid=1000 0 0 "Office-Wifi-1" 70:ba:ef:c6:00:71 rssi=-37 f=2462 sc=100 link=72 tx=0.1, 0.0, 0.0  rx=2.6 bcn=0 [on:0 tx:0 rx:0 period:974] from screen [on:0 period:2136171966] gl u24 rssi=-35 ag=0 hr ls-=0 [56,56,56,56,61] brc=0 lrc=0
10-19 16:59:43.410    3369-3509/? E/WifiStateMachine﹕ L2ConnectedState !RSSI_PKTCNT_FETCH uid=1000 0 0 "Office-Wifi-1" 70:ba:ef:c6:00:71 rssi=-37 f=2462 sc=100 link=72 tx=0.1, 0.0, 0.0  rx=2.6 bcn=0 [on:0 tx:0 rx:0 period:3] from screen [on:0 period:2136171969] gl u24 rssi=-35 ag=0 hr ls-=0 [56,56,56,56,61] brc=0 lrc=0
10-19 16:59:43.420    3369-3509/? E/WifiStateMachine﹕ fetchRssiLinkSpeedAndFrequencyNative rssi=-36 linkspeed=72 SSID="Office-Wifi-1"
10-19 16:59:43.850    3369-3509/? E/WifiStateMachine﹕ ConnectedState !CMD_RSSI_POLL 11 0 "Office-Wifi-1" 70:ba:ef:c6:00:71 rssi=-36 f=2462 sc=100 link=72 tx=0.1, 0.0, 0.0  rx=2.6 bcn=0 [on:0 tx:0 rx:0 period:419] from screen [on:0 period:2136172409] gl u24 rssi=-35 ag=0 hr ls-=0 [56,56,56,56,61] brc=0 lrc=0
10-19 16:59:43.850    3369-3509/? E/WifiStateMachine﹕ L2ConnectedState !CMD_RSSI_POLL 11 0 "Office-Wifi-1" 70:ba:ef:c6:00:71 rssi=-36 f=2462 sc=100 link=72 tx=0.1, 0.0, 0.0  rx=2.6 bcn=0 [on:0 tx:0 rx:0 period:1] from screen [on:0 period:2136172410] gl u24 rssi=-35 ag=0 hr ls-=0 [56,56,56,56,61] brc=0 lrc=0
10-19 16:59:43.860    3369-3509/? E/WifiStateMachine﹕ fetchRssiLinkSpeedAndFrequencyNative rssi=-37 linkspeed=72 SSID="Office-Wifi-1"
10-19 16:59:43.860    3369-3509/? E/WifiStateMachine﹕ calculateWifiScore freq=2462 speed=72 score=100 highRSSI  -> txbadrate=0.00 txgoodrate=0.07 txretriesrate=0.00 rxrate=3.80 userTriggerdPenalty0
10-19 16:59:43.860    3369-3509/? E/WifiStateMachine﹕ good link -> stuck count =0
10-19 16:59:43.860    3369-3509/? E/WifiStateMachine﹕ badRSSI count0 lowRSSI count0 --> score 56
10-19 16:59:43.860    3369-3509/? E/WifiStateMachine﹕ isHighRSSI       ---> score=61
10-19 16:59:44.360    6482-6482/? I/wpa_supplicant﹕ wlan0: HEART-BEAT-ACK: 840
10-19 16:59:44.370    3369-6532/? E/WifiMonitor﹕ WifiMonitor:wlan0 cnt=3254 dispatchEvent: HEART-BEAT-ACK: 840
10-19 16:59:44.370    3369-3509/? E/WifiStateMachine﹕ ConnectedState !what:147506 0 0
10-19 16:59:44.370    3369-3509/? E/WifiStateMachine﹕ L2ConnectedState !what:147506 0 0
10-19 16:59:44.370    3369-3509/? E/WifiStateMachine﹕ ConnectModeState !what:147506 0 0
10-19 16:59:44.370    3369-3509/? E/WifiStateMachine﹕ DriverStartedState !what:147506 0 0
10-19 16:59:44.370    3369-3509/? E/WifiStateMachine﹕ SupplicantStartedState !what:147506 0 0
10-19 16:59:44.400    3369-3369/? I/TrafficMonitor﹕ update:rxPkts:0,txPkts:0,rxBytes:0,txBytes:0
10-19 16:59:44.400    3369-3369/? I/TrafficMonitor﹕ start expired. level:-1
```

不知道大神是否能提供些debug的思路。

**Comment by logan676** [comment]
see also sinaweibosdk/weibo_android_sdk#101

**Comment by logan676** [comment]
还有一类异常的日志是和华为P8 rom相关的

```
10-19 17:14:18.200    4021-5302/? I/HwSystemManager﹕ HoldService:checkBeforeShowDialog: uid:10103 pid:23141, permissionType:16
10-19 17:14:18.200    4021-5302/? I/HwSystemManager﹕ OverseaCfgHelper:permissionStatus is 0
10-19 17:14:18.200    4021-5302/? I/HwSystemManager﹕ ShareLib:pkgNameList:1
10-19 17:14:18.200    4021-5302/? I/HwSystemManager﹕ ShareLib:getApplication pkgName:com.sina.weibo.sdk.demo
10-19 17:14:18.200    4021-5302/? I/HwSystemManager﹕ ShareLib:getAppInfo the final pkgName:com.sina.weibo.sdk.demo
10-19 17:14:18.200    4021-5302/? I/HwSystemManager﹕ ShareLib:getAppInfo time consume:2
10-19 17:14:18.200    4021-5302/? I/HwSystemManager﹕ ShareLib:getAppInfoByUidAndPid time consume:6
10-19 17:14:18.210    4021-5302/? I/HwSystemManager﹕ HoldService:preHoldShow start!
10-19 17:14:18.210    4021-5302/? I/HwSystemManager﹕ HoldService:The prePermissionType is: 1
10-19 17:14:18.210    4021-4441/? I/HwSystemManager﹕ HoldService:checkBeforeShowDialog: uid:10103 pid:23141, permissionType:16
10-19 17:14:18.210    4021-4441/? I/HwSystemManager﹕ OverseaCfgHelper:permissionStatus is 0
10-19 17:14:18.220    4021-4441/? I/HwSystemManager﹕ ShareLib:pkgNameList:1
10-19 17:14:18.220    4021-4441/? I/HwSystemManager﹕ ShareLib:getApplication pkgName:com.sina.weibo.sdk.demo
10-19 17:14:18.220    4021-4441/? I/HwSystemManager﹕ ShareLib:getAppInfo the final pkgName:com.sina.weibo.sdk.demo
10-19 17:14:18.220    4021-4441/? I/HwSystemManager﹕ ShareLib:getAppInfo time consume:5
10-19 17:14:18.220    4021-4441/? I/HwSystemManager﹕ ShareLib:getAppInfoByUidAndPid time consume:8
10-19 17:14:18.230    4021-4441/? I/HwSystemManager﹕ HoldService:preHoldShow start!
10-19 17:14:18.230    4021-4441/? I/HwSystemManager﹕ HoldService:The prePermissionType is: 1
10-19 17:14:18.230    4021-4043/? I/HwSystemManager﹕ HoldService:checkBeforeShowDialog: uid:10103 pid:23141, permissionType:16
10-19 17:14:18.230    4021-4043/? I/HwSystemManager﹕ OverseaCfgHelper:permissionStatus is 0
10-19 17:14:18.240    4021-4043/? I/HwSystemManager﹕ ShareLib:pkgNameList:1
10-19 17:14:18.240    4021-4043/? I/HwSystemManager﹕ ShareLib:getApplication pkgName:com.sina.weibo.sdk.demo
10-19 17:14:18.240    4021-4043/? I/HwSystemManager﹕ ShareLib:getAppInfo the final pkgName:com.sina.weibo.sdk.demo
10-19 17:14:18.240    4021-4043/? I/HwSystemManager﹕ ShareLib:getAppInfo time consume:2
10-19 17:14:18.240    4021-4043/? I/HwSystemManager﹕ ShareLib:getAppInfoByUidAndPid time consume:4
10-19 17:14:18.240    4021-4043/? I/HwSystemManager﹕ HoldService:preHoldShow start!
10-19 17:14:18.240    4021-4043/? I/HwSystemManager﹕ HoldService:The prePermissionType is: 1
10-19 17:14:18.250    3369-3933/? W/System.err﹕ java.lang.SecurityException: WifiService: Neither user 10103 nor current process has android.permission.CHANGE_WIFI_STATE.
10-19 17:14:18.250    3369-3933/? W/System.err﹕ at android.app.ContextImpl.enforce(ContextImpl.java:1960)
10-19 17:14:18.250    3369-3933/? W/System.err﹕ at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1989)
10-19 17:14:18.250    3369-3933/? W/System.err﹕ at com.android.server.wifi.WifiServiceImpl.enforceChangePermission(WifiServiceImpl.java:773)
10-19 17:14:18.250    3369-3933/? W/System.err﹕ at com.android.server.wifi.WifiServiceImpl.getWifiServiceMessenger(WifiServiceImpl.java:1859)
10-19 17:14:18.250    3369-3933/? W/System.err﹕ at android.net.wifi.IWifiManager$Stub.onTransact(IWifiManager.java:495)
10-19 17:14:18.250    3369-3933/? W/System.err﹕ at com.android.server.wifi.HwWifiService.onTransact(HwWifiService.java:61)
10-19 17:14:18.250    3369-3933/? W/System.err﹕ at android.os.Binder.execTransact(Binder.java:446)
```

**Comment by logan676** [comment]
在MX5 Flyme 4.5.x系列机型上的崩溃日志

```
(standard input):8322:V/InputMethodManager(15909): START INPUT: com.android.internal.policy.impl.PhoneWindow$DecorView{3e2faf24 V.E..... R.....ID 0,0-1080,1920} ic=null tba=android.view.inputmethod.EditorInfo@31e2d2ab controlFlags=#104
(standard input):9652:W/InputDispatcher(  865): channel '3a01768c com.sina.weibo.sdk.demo/com.sina.weibo.sdk.demo.WBDemoMainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
(standard input):9654:W/InputDispatcher(  865): channel '3017e68d com.sina.weibo.sdk.demo/com.sina.weibo.sdk.demo.WBAuthActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0xd
(standard input):9663:W/InputDispatcher(  865): Attempted to unregister already unregistered input channel '3017e68d com.sina.weibo.sdk.demo/com.sina.weibo.sdk.demo.WBAuthActivity (server)'
(standard input):9708:W/InputDispatcher(  865): Attempted to unregister already unregistered input channel '3a01768c com.sina.weibo.sdk.demo/com.sina.weibo.sdk.demo.WBDemoMainActivity (server)'
(standard input):9802:V/InputMethodManager( 4266): START INPUT: com.android.internal.policy.impl.PhoneWindow$DecorView{2e89c02f V.E..... R.....ID 0,0-1080,1920} ic=null tba=android.view.inputmethod.EditorInfo@3c6966f6 controlFlags=#104
```

**Comment by yongjhih** [comment]
這些 log 我無法確定與崩潰 callstack 關鍵。列出在哪些機型測試成功與否。
- v3.1.1 Nexus5 android 5.0 正常

另外我將跟進 3.1.2 ，到時可再試。

**Comment by yongjhih** [comment]
v3.1.2 版本的 demo apk:
https://github.com/8tory/weibo-android-sdk/releases/download/3.1.2/weibo-android-sdk-demo-debug.apk

**Comment by logan676** [comment]
> v3.1.1 Nexus5 android 5.0 正常

v3.1.1 Nexus6 android 5.1.1也正常，应该说大部分机型都正常。我会继续跟进这个问题

**Comment by logan676** [comment]
更新了下调用API的代码块问题解决，但是很奇怪的是官方文档中下载SDK的地址竟然指向的是[mobileresearch/weibo_android_sdk](https://github.com/mobileresearch/weibo_android_sdk)。刚才又试了下改成了[sinaweibosdk/weibo_android_sdk](https://github.com/sinaweibosdk/weibo_android_sdk)。哎，凌乱了，到底是以前我弄错了还是新浪微博SDK坑太多。

**Comment by yongjhih** [comment]
你可以試用這裡 sdk(com.infstory:weibo-android-sdk:3.1.2) 編譯你的 apk 或者上方用其 sdk 編譯出來的 demo apk, https://github.com/8tory/weibo-android-sdk/releases/download/3.1.2/weibo-android-sdk-demo-debug.apk 檢驗
